site_name: Cubyz Wiki
use_directory_urls: false
repo_url: https://github.com/iNiKKo/Cubyz-Wiki
repo_name: iNiKKo/Cubyz-Wiki
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - navigation.path
    - toc.integrate
    - navigation.tracking
    - navigation.indexes
    - content.action.edit

plugins:
  - search
  - offline

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 2

extra_css:
  - css/infobox.css
